//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://amt.rnss.rabobank.nl/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://amt.rnss.rabobank.nl/", IsNullable = false)]
public partial class FundsOfMandatesData
{

    private FundOfMandates[] fundsOfMandatesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("FundOfMandates", IsNullable = false)]
    public FundOfMandates[] FundsOfMandates
    {
        get
        {
            return this.fundsOfMandatesField;
        }
        set
        {
            this.fundsOfMandatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://amt.rnss.rabobank.nl/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://amt.rnss.rabobank.nl/", IsNullable = false)]
public partial class FundOfMandates
{

    private string instrumentCodeField;

    private string instrumentNameField;

    private decimal liquidityAllocationField;

    private Mandate[] mandatesField;

    /// <remarks/>
    public string InstrumentCode
    {
        get
        {
            return this.instrumentCodeField;
        }
        set
        {
            this.instrumentCodeField = value;
        }
    }

    /// <remarks/>
    public string InstrumentName
    {
        get
        {
            return this.instrumentNameField;
        }
        set
        {
            this.instrumentNameField = value;
        }
    }

    /// <remarks/>
    public decimal LiquidityAllocation
    {
        get
        {
            return this.liquidityAllocationField;
        }
        set
        {
            this.liquidityAllocationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Mandate", IsNullable = false)]
    public Mandate[] Mandates
    {
        get
        {
            return this.mandatesField;
        }
        set
        {
            this.mandatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://amt.rnss.rabobank.nl/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://amt.rnss.rabobank.nl/", IsNullable = false)]
public partial class Mandate
{

    private string mandateIdField;

    private string mandateNameField;

    private decimal allocationField;

    /// <remarks/>
    public string MandateId
    {
        get
        {
            return this.mandateIdField;
        }
        set
        {
            this.mandateIdField = value;
        }
    }

    /// <remarks/>
    public string MandateName
    {
        get
        {
            return this.mandateNameField;
        }
        set
        {
            this.mandateNameField = value;
        }
    }

    /// <remarks/>
    public decimal Allocation
    {
        get
        {
            return this.allocationField;
        }
        set
        {
            this.allocationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://amt.rnss.rabobank.nl/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://amt.rnss.rabobank.nl/", IsNullable = false)]
public partial class FundsOfMandates
{

    private FundOfMandates[] fundOfMandatesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FundOfMandates")]
    public FundOfMandates[] FundOfMandates
    {
        get
        {
            return this.fundOfMandatesField;
        }
        set
        {
            this.fundOfMandatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://amt.rnss.rabobank.nl/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://amt.rnss.rabobank.nl/", IsNullable = false)]
public partial class Mandates
{

    private Mandate[] mandateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Mandate")]
    public Mandate[] Mandate
    {
        get
        {
            return this.mandateField;
        }
        set
        {
            this.mandateField = value;
        }
    }
}
